language: python
python:
- '2.7'
- '3.6'
install:
- pip install tox-travis
jobs:
  include:
    - stage: "Tests"
      name: "Unit Tests"
      script: tox
    - script: tox -c tox-integration.ini
      name: "Integration Tests"
before_install:
- openssl aes-256-cbc -K $encrypted_b62a2178dc70_key -iv $encrypted_b62a2178dc70_iv
  -in client_secret.json.enc -out client_secret.json -d
