language: python
cache: pip
python:
  - '2.7'
  - '3.6'
install: pip install tox-travis
script: tox
jobs:
  include:
    # TODO de-duplicate this
    - python: '2.7'
      name: "Integration Tests 2.7"
      before_install:
        - openssl aes-256-cbc -K $encrypted_b62a2178dc70_key
          -iv $encrypted_b62a2178dc70_iv -in client_secret.json.enc
          -out client_secret.json -d
      install: pip install tox-travis
      script: tox -c ./tox-integration.ini
    - python: '3.6'
      name: "Integration Tests 3.6"
      before_install:
        - openssl aes-256-cbc -K $encrypted_b62a2178dc70_key
          -iv $encrypted_b62a2178dc70_iv -in client_secret.json.enc
          -out client_secret.json -d
      install: pip install tox-travis
      script: tox -c ./tox-integration.ini
